### ISSUE TITLE
Implement autoupdating

### ISSUE THREAD

**Issue by TheLeonelus** [TheLeonelus/AutoRecord#10]
We need to move-on from unzip.bat in favor of more sustainable solution.

We can use something like GET request to api endpoint, which will answer e.g.:
{
    "Version": "1.0.0"
}
Program can compare it to version of itself, so it can  decide, whenever is update required. 

If update is required we can order script to run unzip.bat to download and install new version.

**Comment by PavelLange666** [comment]
- [ ] Make a scrip to check latest version (for now just notification)
- [ ] pick how to realise an updating, update by yourself or just notificate about newer version
